services:
  nestapp:
    build: ./
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata: